### ISSUE TITLE
No top case in the 3D models

### ISSUE THREAD

**Issue by GPSFan** [crazycaleb2008/T3rminal#1]
Nice project, but  the top case .3mf contains no model, and the .step has no top case either.

**Comment by tuftsanti** [comment]
I found the same, I hope you can include them soon!

**Comment by Serving0firving** [comment]
Same here

**Comment by cbartholomew** [comment]
+1 - The top case isn't working correctly. I tried to load the step file, but somewhere the model hangs up. It would be great if we could get the top as the rest of it printed successfully.

**Comment by tuftsanti** [comment]
Anyone want to design it and resupply?

**Comment by cbartholomew** [comment]
So, I was trying. I've never done modeling before,  so I had to look up some tutorials. 

The measurements for the keyboard and monitor are follows

Keyboard: 
X: 11.5 cm
Y: 6 cm

Entire Monitor (with border):
X: 12 cm
Y: 7.5 cm

However, the screen itself without black border: the measurement from the top would be 1.7cm from the top of the entire unit (inserted) and 1 cm from the side. Here's a picture of what I mean:

![IMG_2954](https://github.com/crazycaleb2008/T3rminal/assets/962366/08fe4930-a577-453c-94e7-0ef4b9acd83f)

So if you wanted to cut a hole for just the screen (not the border), you'd go down from the top approx 1.7cm, and 1cm from the side. 

I'll continue to try my luck w/ fusion, but hopefully this can help some more talented people out.

**Comment by GPSFan** [comment]
New update contains the same non existent top case, the .step is still missing the top case.
the 3dmodel.model file is only 682 bytes.
Which has no model code in it.

**Comment by tuftsanti** [comment]
Could you please consider providing the complete mode so we can extract the top case?

**Comment by cmhduck** [comment]
sorry for the delay I took a break from the project and just saw these comments. every time I did it it worked for me, but I'm going to try to re-upload them

**Comment by cmhduck** [comment]
topcase v2 is uploaded in T3rminal v13 and works fine now. for some reason it would not work unless it was a stl not 3mf. again sorry for not responding soon

**Comment by GPSFan** [comment]
That did it, Thanks.

**Comment by cbartholomew** [comment]
Yup, confirmed this is working now too - thanks again!
